CREATE ROLE airport_app LOGIN PASSWORD 'test' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE airport
  WITH OWNER=airport_app
  ENCODING = 'UTF8'
  TABLESPACE = pg_default
  CONNECTION LIMIT = -1;

\connect airport;

CREATE SCHEMA airport;

CREATE EXTENSION postgis WITH SCHEMA airport;
CREATE EXTENSION pgrouting WITH SCHEMA airport;
CREATE EXTENSION cube WITH SCHEMA airport;
CREATE EXTENSION earthdistance WITH SCHEMA airport;

ALTER DATABASE airport SET SEARCH_PATH TO airport;
GRANT CONNECT ON DATABASE airport TO airport_app;
ALTER ROLE airport_app IN DATABASE airport SET SEARCH_PATH TO airport;


CREATE TABLE airport.airport (
	id BIGINT NOT NULL,
	iata VARCHAR(3),
	icao VARCHAR(4) NOT NULL,
	latitude DOUBLE PRECISION NOT NULL,
	longitude DOUBLE PRECISION NOT NULL
);

COMMENT ON COLUMN airport.airport.id IS 'Airport ID	Unique OpenFlights identifier for this airport.';
COMMENT ON COLUMN airport.airport.iata IS '3-letter IATA code. Null if not assigned/unknown.';
COMMENT ON COLUMN airport.airport.icao IS '4-letter ICAO code.';
COMMENT ON COLUMN airport.airport.latitude IS 'Latitude	Decimal degrees, usually to six significant digits. Negative is South, positive is North.';
COMMENT ON COLUMN airport.airport.longitude IS 'Longitude	Decimal degrees, usually to six significant digits. Negative is West, positive is East.';

CREATE TABLE airport.airport_route (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	source_id BIGINT NOT NULL,
	destination_id BIGINT NOT NULL,
	distance INTEGER
);

COMMENT ON COLUMN airport.airport_route.source_id IS 'Reference to airport.';
COMMENT ON COLUMN airport.airport_route.destination_id IS 'Reference to airport.';
COMMENT ON COLUMN airport.airport_route.distance IS 'Numeric distance between source and destination.';

CREATE TABLE airport.temp_airport (
	id VARCHAR,
	name VARCHAR,
	city VARCHAR,
	country VARCHAR,
	iata VARCHAR,
	icao VARCHAR,
	latitude VARCHAR,
	longitude VARCHAR,
	altitude VARCHAR,
	timezone VARCHAR,
	dst VARCHAR,
	tz_database_time_zone VARCHAR,
	type VARCHAR,
	source VARCHAR
);

COPY airport.temp_airport (
	id,
	name,
	city,
	country,
	iata,
	icao,
	latitude,
	longitude,
	altitude,
	timezone,
	dst,
	tz_database_time_zone,
	type,
	source
) FROM '../airports.dat'
DELIMITER ','
CSV HEADER;

INSERT INTO airport.airport
(
	id,
	iata,
	icao,
	latitude,
	longitude
) SELECT id::BIGINT, iata, icao, latitude::DOUBLE PRECISION, longitude::DOUBLE PRECISION FROM airport.temp_airport;

DROP TABLE airport.temp_airport;

UPDATE airport.airport SET iata = NULL WHERE iata = '\N';

CREATE TABLE airport.temp_airport_route (
	airline VARCHAR,
	airline_id VARCHAR,
	source VARCHAR,
	source_id VARCHAR,
	destination VARCHAR,
	destination_id VARCHAR,
	codeshare VARCHAR,
	stops VARCHAR,
	equipment VARCHAR
);

COPY airport.temp_airport_route (
	airline,
	airline_id,
	source,
	source_id,
	destination,
	destination_id,
	codeshare,
	stops,
	equipment
) FROM '../routes.dat'
DELIMITER ','
CSV HEADER;

UPDATE airport.temp_airport_route SET source_id = NULL WHERE source_id = '\N';
UPDATE airport.temp_airport_route SET destination_id = NULL WHERE destination_id = '\N';

INSERT INTO airport.airport_route
(
	source_id,
	destination_id
)
SELECT
		source_id::BIGINT,
		destination_id::BIGINT
FROM airport.temp_airport_route
WHERE source_id IS NOT NULL AND destination_id IS NOT NULL;

DROP TABLE airport.temp_airport_route;

GRANT USAGE ON SCHEMA airport TO airport_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA airport TO airport_app;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA airport TO airport_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA airport TO airport_app;
